# Generated by Django 5.1.6 on 2025-03-28 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioVT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Tratamiento', 'Tratamiento'), ('Vacuna', 'Vacuna')], default='Tratamiento', max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('unidades', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('cantidad', models.CharField(choices=[('Sobre', 'Sobre'), ('Botella', 'Botella')], default='Sobre', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Toro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Vivo', 'Vivo'), ('Muerte', 'Muerte'), ('Otros', 'Otros')], default='Vivo', max_length=15)),
                ('cantidad_semen', models.IntegerField()),
                ('transmision_leche', models.DecimalField(decimal_places=2, max_digits=4)),
                ('celulas_somaticas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calidad_patas', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('calidad_ubres', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('grasa', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Vaca', 'Vaca'), ('Ternero', 'Ternero')], default='Vaca', max_length=15)),
                ('estado', models.CharField(choices=[('Vacía', 'Vacía'), ('Inseminada', 'Inseminada'), ('Preñada', 'Preñada'), ('No inseminar', 'No inseminar'), ('Joven', 'Joven'), ('Muerta', 'Muerta'), ('Vendida', 'Vendida')], default='Vacía', max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('celulas_somaticas', models.IntegerField(validators=[django.core.validators.MinValueValidator(50000), django.core.validators.MaxValueValidator(2000000)])),
                ('produccion_leche', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('calidad_patas', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('calidad_ubres', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('grasa', models.FloatField(validators=[django.core.validators.MinValueValidator(2.5), django.core.validators.MaxValueValidator(6)])),
                ('proteinas', models.FloatField(validators=[django.core.validators.MinValueValidator(2.8), django.core.validators.MaxValueValidator(4)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='ganaderiaBovina.animal')),
                ('corral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='ganaderiaBovina.corral')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='ganaderiaBovina.toro')),
            ],
        ),
        migrations.CreateModel(
            name='ListaInseminaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Inseminacion', 'Inseminacion')], default='Inseminacion', max_length=15)),
                ('razon', models.CharField(choices=[('Celo', 'Celo'), ('Programada', 'Programada')], default='Celo', max_length=15)),
                ('fecha_inseminacion', models.DateField()),
                ('hora_inseminacion', models.TimeField()),
                ('es_sexado', models.BooleanField()),
                ('responsable', models.CharField(max_length=100)),
                ('id_vaca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderiaBovina.animal')),
                ('id_toro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderiaBovina.toro')),
            ],
        ),
        migrations.CreateModel(
            name='VTAnimales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Tratamiento', 'Tratamiento'), ('Vacuna', 'Vacuna')], default='Tratamiento', max_length=15)),
                ('nombre_vt', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta', models.CharField(choices=[('Intravenosa', 'Intravenosa'), ('Intramamaria', 'Intramamaria'), ('Intramuscular', 'Intramuscular'), ('Intravaginal', 'Intravaginal'), ('Oral', 'Oral'), ('Nasal', 'Nasal'), ('Subcutánea', 'Subcutánea')], default='Intravenosa', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('responsable', models.CharField(max_length=100)),
                ('dosis', models.IntegerField()),
                ('id_animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderiaBovina.animal')),
                ('inventario_vt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderiaBovina.inventariovt')),
            ],
        ),
    ]
