# Generated by Django 5.1.6 on 2025-03-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='corral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='ganaderiaBovina.corral'),
        ),
    ]
