# Generated by Django 5.1.6 on 2025-03-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0002_alter_animal_corral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='corral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='ganaderiaBovina.corral'),
        ),
    ]
