# Generated by Django 5.1.6 on 2025-03-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0003_alter_animal_corral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
