# Generated by Django 5.1.6 on 2025-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0004_alter_animal_fecha_eliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toro',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
