# Generated by Django 5.1.6 on 2025-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0006_remove_vtanimales_nombre_vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
