# Generated by Django 5.1.6 on 2025-03-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0008_alter_corral_codigo_alter_inventariovt_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariovt',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=15),
        ),
        migrations.AlterField(
            model_name='vtanimales',
            name='inventario_vt',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='ganaderiaBovina.inventariovt'),
            preserve_default=False,
        ),
    ]
