# Generated by Django 5.1.6 on 2025-04-02 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0009_inventariovt_estado_alter_vtanimales_inventario_vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toro',
            name='celulas_somaticas',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='toro',
            name='transmision_leche',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
