# Generated by Django 5.1.6 on 2025-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0010_alter_toro_celulas_somaticas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toro',
            name='celulas_somaticas',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='toro',
            name='transmision_leche',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
