# Generated by Django 5.1.6 on 2025-04-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0011_alter_toro_celulas_somaticas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtanimales',
            name='inventario_vt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ganaderiaBovina.inventariovt'),
        ),
    ]
