# Generated by Django 5.1.6 on 2025-04-07 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0012_alter_vtanimales_inventario_vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toro',
            name='cantidad_semen',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
