# Generated by Django 5.1.6 on 2025-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0013_alter_toro_cantidad_semen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corral',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
