# Generated by Django 5.1.6 on 2025-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0014_alter_corral_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listainseminaciones',
            name='es_sexado',
            field=models.BooleanField(default=True),
        ),
    ]
