# Generated by Django 5.1.6 on 2025-04-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0015_alter_listainseminaciones_es_sexado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toro',
            name='fecha_eliminacion',
        ),
    ]
