# Generated by Django 5.1.6 on 2025-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0016_remove_toro_fecha_eliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('Vacía', 'Vacía'), ('Inseminada', 'Inseminada'), ('Preñada', 'Preñada'), ('No inseminar', 'No inseminar'), ('Joven', 'Joven'), ('Muerte', 'Muerte'), ('Vendida', 'Vendida')], default='Vacía', max_length=15),
        ),
    ]
