# Generated by Django 5.1.6 on 2025-04-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0017_alter_animal_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtanimales',
            name='dosis',
        ),
    ]
