# Generated by Django 5.1.6 on 2025-04-30 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0018_remove_vtanimales_dosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariovt',
            name='unidades',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
