# Generated by Django 5.1.6 on 2025-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0019_alter_inventariovt_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toro',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
