# Generated by Django 5.1.6 on 2025-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderiaBovina', '0020_alter_toro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariovt',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
